
<section class="about-us">
   <div class="abouOverlay">
      <div class="container">
            <div class="col-md-12">
               <h2 style="color: #8500A8;">Terms And Conditions</h2>
               <hr style="border: 1px solid black">
            </div>
            <div class="col-md-12">
               <ul style="color:black;">
                  <li> <h5 style="text-align: justify; color: black">Doer or thinker (DOT) scholarship. These Terms & Conditions (“Terms”) of (a) use of our website doerorthinker.com (“Website”)</h5></li><br>
                  <li> <h5 style="text-align: justify; color: black">Please read the Terms and the privacy policy of the Company (“Privacy Policy”) with respect to registration with us, the use of the Application, Website, Services and products carefully before using the Application, Website, Services or products. In the event of any discrepancy between the Terms and any other policies with respect to the Application or Website or Services or products, the provisions of the Terms shall prevail.</h5></li><br>
                  <li> <h5 style="text-align: justify; color: black">This scholarship prize money is only for their educational purpose.</h5></li><br>
                  <li> <h5 style="text-align: justify; color: black">Scholarship amount will be given to the students in monthly basis in the name of their educational expenses.</h5></li><br>
                  <li><h5 style="text-align: justify; color: black"> For the topper student-- 15lakh rupees will be used in his/her upsc preparation only, which covers his all  educational expenses, hostel facility, laptop cost and other daily basis required expenses. And all the benefits which he/she gets will be covered in scholarship prize money(Rs15lakh/-)</h5></li><br>
                  <li><h5 style="text-align: justify; color: black"> In case of tie marks younger student will get selection for the prize money.</h5></li><br>
                  <li><h5 style="text-align: justify; color: black"> Number of winning candidates may increase or decrease with the number of registrations.</h5></li><br>
                  <li><h5 style="text-align: justify; color: black">  Exam may postpone in case of pandemic like covid-19 or less number of registrations.</h5></li><br>
                  <li><h5 style="text-align: justify; color: black">  There may come some other changes as per situations.</h5></li><br>
                  <li><h5 style="text-align: justify; color: black">   This Terms and Privacy Policy applies to all of the products, services offered by doerorthinker.com  or its subsidiaries. If you have any questions about this Privacy Policy, please feel free to contact us through our website or write to us at doerorthinker@gmail.com</h5></li><br>
                  <li><h5 style="text-align: justify; color: black">In case of any conflict/dispute about rank, decision of the DOT Academic Council will be final & binding.</h5></li><br>
                  <li><h5 style="text-align: justify; color: black"> Result: The final result of DOT exam will be published on the site. Students can login to their account and check their final result.</h5></li><br>
                  <li><h5 style="text-align: justify; color: black"> Display of participants name / photograph / interview: DOT reserves the right to display, reproduce, adapt, modify, publish, distribute, publicly perform, create a derivative work from, and publicly display the participants photograph for any purpose, including display on the DOT website, social media platforms, news and partner sites.</h5></li><br>
                  <li><h5 style="text-align: justify; color: black"> Answer-Sheet: DOT will discard the answer-sheet of the students after one month since the result is declared according to the company policies. Any queries regarding the same will not be entertained.</h5></li><br>
                  <li><h5 style="text-align: justify; color: black">Certificate: Certificate or medal / shield will be re-issued to the student only after collecting the prescribed re-issue fees.</h5></li><br>
                  <li><h5 style="text-align: justify; color: black">Privacy of our staff/associates/team: For the privacy and safety of our team, staffs and associates, under no circumstances, we will be disclosing the details of our team/associates involved in the creation of training material, contents, question papers, evaluation of answer-sheet and interview.</h5></li><br>

                   <li><h5 style="text-align: justify; color: black">Notwithstanding anything mentioned in the site or communicated to the student/parent the DOT may adopt for purposes of scoring / ranking / evaluating any particular cases or class of cases a special procedure as more appropriate than the one prescribed in any of the rules specified.</h5></li><br>

                    <li><h5 style="text-align: justify; color: black"> Conflict: In case of any dispute / conflict related to syllabus / question / answer / marking scheme/ result / ranking / selection process, decision of the DOT Academic Council will be final & binding.</h5></li><br>

                     <li><h5 style="text-align: justify; color: black"> Information we collect and how we use it:: We may collect the following types of information: Information you provide: When you sign up for a subscription or register for exam, we ask you for personal information. We may combine the information you submitted under your account with information from other DOT services or third parties in order to provide you with a better experience and to improve the quality of our services.</h5></li><br>

                      <li><h5 style="text-align: justify; color: black">Photos and Testimony: DOTS will have royalty-free rights to all submitted user photographs and videos. DOT can use, reproduce, adapt, modify, publish, distribute, publicly perform, create a derivative work from, and publicly display the interview/photograph for any purpose, including display on the DOT website, social media platforms, news and partner sites.</h5></li><br>

                       <li><h5 style="text-align: justify; color: black"> Log information: When you access our services via a browser, application or other client, our servers automatically record certain information. These server logs may include information such as your web request, your interaction with a service, Internet Protocol address, browser type, browser language, the date and time of your request and one or more cookies that may uniquely identify your browser or your account.</h5></li><br>

                       <li><h5 style="text-align: justify; color: black"> Performance information: When you take a test, we store your submitted answer and your performance in the test.</h5></li><br>

                       <li><h5 style="text-align: justify; color: black"> User communications: When you send email or other communications to DOT, we may retain those communications in order to process your inquiries, respond to your requests and improve our services. We may use your email address to communicate with you about our services.</h5></li><br>

                       <li><h5 style="text-align: justify; color: black"> In addition to the above, we may use the information we collect to:                             Provide, maintain, protect, and improve our services and develop new services; and Protect the rights or property of DOT or our users.</h5></li><br>

                       <li><h5 style="text-align: justify; color: black"> Information sharing:: We only shares personal information with other companies or individuals outside of our group of companies in the following limited circumstances: We have your consent. We require opt-in consent for the sharing of any sensitive personal information.</h5></li><br>

                       <li><h5 style="text-align: justify; color: black"> We provide such information to our subsidiaries, affiliated companies or other trusted businesses or persons for the purpose of processing personal information on our behalf. We require that these parties agree to process such information based on our instructions and in compliance with this Privacy Policy and any other appropriate confidentiality and security measures.</h5></li><br>

                       <li><h5 style="text-align: justify; color: black"> We have a good faith belief that access, use, preservation or disclosure of such information is reasonably necessary to <br> (a) satisfy any applicable law , regulation, legal process or enforceable governmental request, <br>(b) enforce applicable Terms of Service, including investigation of potential violations thereof, <br>(c) detect, prevent, or otherwise address fraud, security or technical issues, or <br>(d) protect against harm to the rights, property or safety of DOT or its users or the public as required or permitted by law.</h5></li><br>

                       <li><h5 style="text-align: justify; color: black"> We restrict access to personal information to DOT employees, contractors and agents who need to know that information in order to process it on our behalf. These individuals are bound by confidentiality obligations and may be subject to discipline, including termination and criminal prosecution, if they fail to meet these obligations.We take appropriate security measures to protect against unauthorized access to or unauthorized alteration, disclosure or destruction of data. These include internal reviews of our data collection, storage and processing practices and security measures, including appropriate encryption and physical security measures to guard against unauthorized access to systems where we store personal data.</h5></li><br>

                       <li><h5 style="text-align: justify; color: black">  We take appropriate security measures to protect against unauthorized access to or unauthorized alteration, disclosure or destruction of data. These include internal reviews of our data collection, storage and processing practices and security measures, including appropriate encryption and physical security measures to guard against unauthorized access to systems where we store personal data.</h5></li><br>

                       <li><h5 style="text-align: justify; color: black">We restrict access to personal information to DOT, contractors and agents who need to know that information in order to process it on our behalf. These individuals are bound by confidentiality obligations and may be subject to discipline, including termination and criminal prosecution, if they fail to meet these obligations.</h5></li><br>

                       <li><h5 style="text-align: justify; color: black">  Limitation of Liability::    DOT will not be liable for any or all damages of whatsoever nature, including but not limited to direct, indirect, general, special, compensatory, consequential, and/or incidental, arising out of or relating to the test results or test scores. Nothing contained in this Website or in any written or oral communications from doerorthinker.com or its employees or agents shall be construed to make any promise, covenant, warranty, or guaranty, all of which are explicitly disclaimed hereby, contrary to the statements and disclaimers contained in this paragraph.</h5></li><br>

                       <li><h5 style="text-align: justify; color: black">The content and functionality on the Website and the services provided by employees of the Website are offered "as is" without warranty of any kind, either express or implied, including, without limitation, implied warranties of merchantability, fitness for a particular purpose, title and non-infringement. DOT makes no warranties, express or implied, as to the ownership, accuracy, completeness or adequacy of the Website content or that the functionality of the Website will be uninterrupted or error-free or free from virus or third party attack. You hereby acknowledge that use of this Website and the Service is at your sole risk.</h5></li><br>

                       <li><h5 style="text-align: justify; color: black"> We restrict access to personal information to ISTSE or Educational Excellentia employees, contractors and agents who need to know that information in order to process it on our behalf. These individuals are bound by confidentiality obligations and may be subject to discipline, including termination and criminal prosecution, if they fail to meet these obligations.</h5></li><br>

                       <li><h5 style="text-align: justify; color: black"> Under no circumstances shall DOT , its officers, owners, employees or agents and their respective heirs, successors and assigns will be held liable for any damages, including direct, incidental, punitive, special, consequential or exemplary damages that directly or indirectly result from use of, or inability to use, the website or service or the information contained therein, including without limitation for viruses alleged to have been obtained from the website, even if doerorthinker.com has been notified of the possibility of such damages or losses and regardless of the theory of liability.</h5></li><br>

                        <li><h5 style="text-align: justify; color: black">  To the greatest extent permitted by law, you agree that in no event will DOT have any liability, contingent or otherwise, for any indirect, special, incidental, consequential, or exemplary damages in any way arising out of or relating to the agreement, website or the service, including, but not limited to lost profits, lost data, loss of goodwill, copyright infringement, work stoppage, equipment failure or malfunction, personal injury, property damage, or any other damages or losses, even if istse.org has been advised of the possibility thereof.</h5></li><br>

                         <li><h5 style="text-align: justify; color: black">  Jurisdiction and Choice of Law; Dispute Resolution:: If there is any dispute arising out of the Website and/or the Service, by using the Website and/or Service, you expressly agree that any such dispute shall be governed by the laws of, India and shall be subject to the exclusive jurisdiction of Bengaluru courts only.</h5></li><br>

                          <li><h5 style="text-align: justify; color: black">Changes to this Term and Privacy Policy:: Please note that this Privacy Policy may change from time to time. We will not reduce your rights under this Privacy Policy without your explicit consent. We will post any Privacy Policy changes on this page and, if the changes are significant, we will provide a more prominent notice (including, for certain services, email notification of Privacy Policy changes). We will also keep prior versions of this Privacy Policy in an archive for your review.</h5></li><br>

                          <li><h5 style="text-align: justify; color: black"> If You do not agree with the Terms or the Privacy Policy, please do not participate in DOT exam and do not use the Application or Website or avail the Services or products.</h5></li><br>

                          <li><h5 style="text-align: justify; color: black">  Any access to our Services/Application/products through registrations/subscription is non transferable.</h5></li><br>

                          <li><h5 style="text-align: justify; color: black"> General Terms of Services: By registering, you permit us to add your email to the newsletter subscription list. You also authorize us to send regular email newsletters on your registered email id. You also allow us to send promotional emails and SMS on your registered email ID and registered mobile number.</h5></li><br>

                          <li><h5 style="text-align: justify; color: black">Using our Apps or Website includes but is not limited to creating an account, purchasing and using Digital Content, posting a review or otherwise viewing, visiting, or using any interactive features on our site/app.</h5></li><br>

                          <li><h5 style="text-align: justify; color: black">The use of the content on our site/app is governed by the terms mentioned below. This includes any Digital Content or any other products and services available for sale on our site/app (collectively called the "Content"), which is the copyrighted work of DOT or our Suppliers.</h5></li><br>

                          <li><h5 style="text-align: justify; color: black">No Content from this site/app may be copied, republished, reproduced, uploaded, posted, transmitted, or distributed in any way other.</h5></li><br>

                           <li><h5 style="text-align: justify; color: black">We reserve the right to change or discontinue the offer of any Digital Content or other products and services. For Digital Content, depending on the Suppliers' terms and conditions, it is possible that after you have successfully purchased a particular Digital Content, that further purchase may not be available, and a refund is not possible.</h5></li><br>

                            <li><h5 style="text-align: justify; color: black">From time to time, we may offer promotional discounts and/ or special offers, subject to change and availability. The discounts and offers apply to listed Digital Content, products, and services and can only be used as specified. Promotional discount codes cannot be used retrospectively and cannot be used with any other offer. We reserve the right to withdraw promotional discounts and/ or special offers at any time.</h5></li><br>

                            <li><h5 style="text-align: justify; color: black">Although the administrators and moderators of DOT will attempt to keep all objectionable messages off this site/app, we can't review all messages. All words express the author's views, and neither the owners of DOT will be held responsible for the content of any message.</h5></li><br>

                            <li><h5 style="text-align: justify; color: black"> By agreeing to these rules, you warrant that you will not post any messages that are obscene, vulgar, sexually-oriented, hateful, threatening, or otherwise violative of any laws.</h5></li><br>

                            <li><h5 style="text-align: justify; color: black"> The owners of the DOT reserve the right to remove, edit, move or close any content item for any reason.</h5></li><br>

                            <li><h5 style="text-align: justify; color: black"> By submitting content on or through the Services (your “Material”), you grant us a worldwide, non-exclusive, royalty-free license (with the right to sublicense) to use, copy, reproduce, process, adapt, modify, publish, transmit, display and distribute such Material in any and all media or distribution methods (now known or later developed) and to associate your Material with you, except as described below. You agree that others may use Your Material in the same way as any other content available through the Services. Other users of the Services may fork, tweak and repurpose your Material in accordance with these Terms. If you delete your user account your Material and name may remain available through the Services.</h5></li><br>

                             <li><h5 style="text-align: justify; color: black"> In the preparation of the Application/Website/Services/products and contents therein, every effort has been made to offer the most current, correct, and clearly expressed information possible. Nevertheless, inadvertent errors may occur. In particular, but without limiting anything here, the Company disclaims any responsibility for any errors and accuracy of the information that may be contained in the Application. Any feedback from User is most welcome to make the Application and contents thereof error free and user friendly. Company also reserves the right and discretion to make any changes/corrections or withdraw/add contents at any time without notice. Neither the Company nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on Application/Website/Services/products for any particular purpose. You acknowledge that such information and materials may contain.</h5></li><br>

                             <li><h5 style="text-align: justify; color: black">  Inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</h5></li><br>

                              <li><h5 style="text-align: justify; color: black">  Our Website provides Users with access to compiled educational information and related sources. Such information is provided on an As Is basis and We assume no liability for the accuracy or completeness or use or non obsolescence of such information. We shall not be liable to update or ensure continuity of such information contained on the Website. We would not beresponsible for any errors, which might appear in such information, which is compiled from third party sources or for any unavailability of such information. From time to time the Website may also include links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the website(s). We have no responsibility for the content of the linked website(s). You may not create a link to the Website from another website or document without the Company’s prior written consent.</h5></li><br>

                               <li><h5 style="text-align: justify; color: black">The contents of the Application/Services/products are developed on the concepts covered in the structured curriculum syllabus prescribed for students of various courses. The usage of the Application/Services/products is not endorsed as a substitution to the curriculum based education provided by the educational institutions but is intended to supplement the same by explaining and presenting the concepts in a manner enabling easy understanding. The basic definitions and formulae of the subject matter would remain the same. The Company acknowledges that there are various means of delivering structured curriculum pedagogy and inclusion of methods in the Application/Services/products does not imply endorsement of any particular method nor exclusion imply disapproval. Subscription to the Application or usage of our Services/Website/products does not in any manner guarantee admission to any educational institutions or passing of any exams or achievement of any specified percentage of marks in any examinations.</h5></li><br>

                                <li><h5 style="text-align: justify; color: black">Certain contents in the Application/Services/Website/products (in particular relating to assistance in preparations for administrative services) may contain opinions and views. The Company shall not be responsible for such opinions or any claims resulting from them. Further, the Company makes no warranties or representations whatsoever regarding the quality, content, completeness, or adequacy of such information and data.</h5></li><br>

                                <li><h5 style="text-align: justify; color: black">Some parts of the Services are interactive, and we encourage contributions by Users, which may or may not be subject to editorial control prior to being posted. The Company accepts no responsibility or liability for any material communicated by third parties in this way. The Company reserves the right at its sole discretion to remove, review, edit or delete any content. Similarly, We will not be responsible or liable for any content uploaded by Users directly on the Website, irrespective of whether We have certified any answer uploaded by the User. We would not be responsible to verify whether such questions/answers or contents placed by any User contain infringing materials or not.</h5></li><br>

                                <li><h5 style="text-align: justify; color: black">The Company may, based on any form of access to the Application (including free download/trials) or Services or Website or registrations through any source whatsoever, contact the User through sms, email and call, to give information about its products as well as notifications on various important updates and/or to seek permission for demonstration of its products. The User expressly grants such permission to contact him/her through telephone, SMS, e-mail and holds the Company indemnified against any liabilities including financial penalties, damages, expenses in case the User’s mobile number is registered with Do not Call (DNC) database. By registering yourself , you agree to make your contact details available to Our employees, associates and partners so that you may be contacted for education information and promotions through telephone, SMS, email etc.</h5></li><br>

                                <li><h5 style="text-align: justify; color: black">While the Company may, based on the User’s confirmation, facilitate the demonstration of its products at the location sought by the User, the User acknowledges that he/she has not been induced by any statements or representations of any person with respect to the quality or conditions of the products and that User has relied solely on the investigations, examinations and inspections.</h5></li><br>

                                <li><h5 style="text-align: justify; color: black">Upon registration through any means whatsoever, the Company may contact You through the registered mobile number or e-mail or any other mobile number or contact number or email provided by You to enable effective provision of Services. The User expressly permits the Company to contact him/her and the student utilising the Services, through the above mentioned means at any time post registration. .-. Further, the Company shall have the right to monitor the download and usage of the Application/Services/products and the contents thereof by the User/student, to analyze such usage and discuss the same with the User/student to enable effective and efficient usage of the Services. The User expressly permits the Company to clear the doubts of the student using the Application/Services/online portal by answering the questions placed before it, providing study plans, informing of the progress, providing feedback, communicating with the student and mentoring the student through telephone or e-mail on express consent of the legal guardian/parent of the User or through any other forum.</h5></li><br>

                                <li><h5 style="text-align: justify; color: black">While the Company has made efforts to train the personnel engaged in the sales and services relating to its products to enable quality control, it makes no warranties or representations whatsoever regarding the quality and competence of such personnel and would not be responsible for any deviant behaviour of any such personnel. Any feedback from User relating to the same is most welcome and Company reserves the right and discretion to take any action in this regard.</h5></li><br>

                                 <li><h5 style="text-align: justify; color: black">Access to certain elements of the Services including doubt clearance, mentoring services etc may be subject to separate terms, conditions and fair usage policy. The Company reserves the right to determine the criteria for provision of various elements of Services to the different categories of Users based on its policies. Hence, subscription to the Application/products or registrations do not automatically entitle the User to any and all elements of Services provided by the Company and the Company shall be entitled to exercise its discretion while providing access to and determining continuity of certain elements of Services. We reserve the right to extend, cancel, discontinue, prematurely withdraw or modify any of Our Services at Our discretion.</h5></li><br>

                                  <li><h5 style="text-align: justify; color: black">You shall be responsible for maintaining the confidentiality of the account information and for all activities that occur under Your account. You agree to<br> (a) ensure that You successfully log out from Your account at the end of each session; and<br> (b) immediately notify the Company of any unauthorized use of Your account. If there is reason to believe that there is likely to be a breach of security or misuse of Your account, we may request You to change the password or we may suspend Your account without any liability to the Company, for such period of time as we deem appropriate in the circumstances. We shall not be liable for any loss or damage arising from Your failure to comply with this provision.</h5></li><br>

                                   <li><h5 style="text-align: justify; color: black">You acknowledge that Your ability to use Your account is dependent upon external factors such as internet service providers and internet network availability and the Company cannot guarantee accessibility to the Application at all times. In addition to the disclaimers set forth in the Terms, the Company shall not be liable to You for any damages arising from Your inability to log into Your account and access the services of the Application at any time.</h5></li><br>

                                    <li><h5 style="text-align: justify; color: black"> You agree to defend, indemnify and hold harmless the Company, its officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from: (i) Your use of and access of the Application/Website/Services; (ii) Your violation of any term of these Terms or any other policy of the Company; (iii) Your violation of any third party right, including without limitation, any copyright, property, or privacy right; or (iv) any claim that Your use of the Application/Website/Services has caused damage to a third party. This defense and indemnification obligation will survive these Terms.</h5></li><br>

                                     <li><h5 style="text-align: justify; color: black"> If You do not agree with the Terms or the Privacy Policy, please do not use the Application or Website or avail the Services or products. Any access to our Services/Application/products through registrations/subscription is non transferable.</h5></li><br>

                                     <li><h5 style="text-align: justify; color: black">  Except as mentioned below, all information, content, material, trademarks, services marks, trade names, and trade secrets including but not limited to the software, text, images, graphics, video, script and audio, contained in the Application, Website, Services and products are proprietary property of the Company (“Proprietary Information”). No Proprietary Information may be copied, downloaded, reproduced, modified, republished, uploaded, posted, transmitted or distributed in any way without obtaining prior written permission from the Company and nothing on this Application or Website or Services shall be or products deemed to confer a license of or any other right, interest or title to or in any of the intellectual property rights belonging to the Company, to the User. You may own the medium on which the information, content or materials resides, but the Company shall at all times retain full and complete title to the information, content or materials and all intellectual  rights insrted by the Company on such medium. Certain contents on the Website may belong to third parties. Such contents have been reproduced after taking prior consent from said party and all rights relating to such content will remain with such third party. Further, you recognize and acknoweldge that the ownership of all trademarks, copyright, logos, service  and other intellectual property owned by any third party shall continue to vest with such party and You are not permitted to use the same without the consent of the respective third party.</h5></li><br>

                                      <li><h5 style="text-align: justify; color: black">  Your use of our products, Website, Application and Services is solely for Your personal and non-commercial use. Any use of the Application, Website, Services or products or their contents other than for personal purposes is prohibited. Your personal and non-commercial use of this Application, Website, products and / or our Services shall be subjected to the following restrictions: You may not decompile, reverse engineer, or disassemble the contents of the Application and / or our Website and/or Services/ products or modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information or software obtained from the Application and / or our Website and/or Services/products, or remove any copyright, trademark registration, or other proprietary notices from the contents of the Application and / or and / or our Website and/or Services/products.</h5></li><br>

                                      <li><h5 style="text-align: justify; color: black">  You will not (a) use this Application and / or our Website and/or any of our product/s or Service/s for commercial purposes of any kind, or (b) advertise or sell the Application or any products, Services or domain names or otherwise (whether or not for profit), or solicit others (including, without limitation, solicitations for contributions or donations) or use any public forum for commercial purposes of any kind, or (c) use the Application and / or Website/our products and Services in any way that is unlawful, or harms the Company or any other person or entity as determined by the Company.</h5></li><br>

                                       <li><h5 style="text-align: justify; color: black">  No User shall be permitted to perform any of the following prohibited activities while availing our Services:</h5></li><br>

                                       <li><h5 style="text-align: justify; color: black">  Making available any content that is misleading, unlawful, harmful, threatening, abusive, tortious, defamatory, libelous, vulgar, obscene, child-pornographic, lewd, lascivious, profane, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable;</h5></li><br>

                                       <li><h5 style="text-align: justify; color: black">  Stalking, intimidating and/or harassing another and/or inciting other to commit violence;</h5></li><br>

                                        <li><h5 style="text-align: justify; color: black">  Transmitting material that encourages anyone to commit a criminal offence, that results in civil liability or otherwise breaches any relevant laws, regulations or code of practice.</h5></li><br>

                                        <li><h5 style="text-align: justify; color: black">  Interfering with any other person's use or enjoyment of the Application/Website/Services.</h5></li><br>

                                         <li><h5 style="text-align: justify; color: black">  Making, transmitting or storing electronic copies of materials protected by copyright without the permission of the owner, committing any act that amounts to the infringement of intellectual property or making available any material that infringes any intellectual property rights or other proprietary rights of anyone else.</h5></li><br>

                                         <li><h5 style="text-align: justify; color: black">  Make available any content or material that You do not have a right to make available under any law or contractual or fiduciary relationship, unless You own or control the rights thereto or have received all necessary consents for such use of the content.</h5></li><br>

                                         <li><h5 style="text-align: justify; color: black">   Impersonate any person or entity, or falsely state or otherwise misrepresent Your affiliation with a person or entity.</h5></li><br>

                                          <li><h5 style="text-align: justify; color: black">  Post, transmit or make available any material that contains viruses, trojan horses, worms, spyware, time bombs, cancelbots, or other computer programming routines, code, files or such other programs that may harm the Application/services, interests or rights of other users or limit the functionality of any computer software, hardware or telecommunications, or that may harvest or collect any data or personal information about other Users without their consent.</h5></li><br>

                                           <li><h5 style="text-align: justify; color: black"> Access or use the Application/Website/Services/products in any manner that could damage, disable, overburden or impair any of the Application’s/Website’s servers or the networks connected to any of the servers on which the Application/Website is hosted.</h5></li><br>

                                           <li><h5 style="text-align: justify; color: black">  Intentionally or unintentionally interfere with or disrupt the services or violate any applicable laws related to the access to or use of the Application/Website/Services/products, violate any requirements, procedures, policies or regulations of networks connected to the Application/Website/Services/products, or engage in any activity prohibited by these Terms.</h5></li><br>

                                           <li><h5 style="text-align: justify; color: black">   Disrupt or interfere with the security of, or otherwise cause harm to, the Application/Website/Services/products, materials, systems resources, or gain unauthorized access to user accounts, passwords, servers or networks connected to or accessible through the Application/Website/Services/products or any affiliated or linked sites.</h5></li><br>

                                           <li><h5 style="text-align: justify; color: black">   Interfere with, or inhibit any user from using and enjoying access to the Application/Website/ Services/products, or other affiliated sites, or engage in disruptive attacks such as denial of service attack on the Application/Website/Services.</h5></li><br>

                                           <li><h5 style="text-align: justify; color: black">Use deep-links, page-scrape, robot, spider or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to increase traffic to the Application/Website/Services/products, to access, acquire, copy or monitor any portion of the Application /Website/Services/products, or in any way reproduce or circumvent the navigational structure or presentation of the Application, or any content, to obtain or attempt to obtain any content, documents or information through any means not specifically made available through the Application/ Website/Services/products.</h5></li><br>

                                           <li><h5 style="text-align: justify; color: black">Use the Services for purposes that are not permitted by: (i) these Terms; and (ii) any applicable law, regulation or generally accepted practices or guidelines in the relevant jurisdiction. or</h5></li><br>

                                           <li><h5 style="text-align: justify; color: black"> Alter or modify any part of the Services.</h5></li><br>

                                           <li><h5 style="text-align: justify; color: black"> Violate any of the terms specified under the Terms for the use of the Application /Website/Services/products.</h5></li><br>

                                           <li><h5 style="text-align: justify; color: black"> Changes to this Terms of Services ---- Please note that this Terms of Services may change from time to time. We will not reduce your rights under this Privacy Policy without your explicit consent. We will post any Privacy Policy changes on this page and, if the changes are significant, we will provide a more prominent notice (including, for certain services, email notification of Terms of Service changes). We will also keep prior versions of this Terms of Services in an archive for your review.</h5></li><br>
               </ul>

              
            </div>
         </div>
      </div>
   </section>